### ISSUE TITLE
Django App is Not Working

### ISSUE THREAD

**Issue by aayushi-droid** [rshrc/django-ml#1]
## Page Not Found At location :
- ```localhost:8000 ```and
- ```localhost:8000/server```

Project doesn't have html template to show.
@rshrc

**Comment by rshrc** [comment]
there is no template supposed to be there. There is just the API which you can see and hit HTTP requests to

**Comment by aayushi-droid** [comment]
I used Django rest framework before but I am not able to find the API. Can you check the Error or guide me the right way.

Getting :

```'GetSalaryAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.```

**Comment by rshrc** [comment]
Kindly visit this url http://localhost:8000/server/api/salary/ on runserver to see the API page

**Comment by aayushi-droid** [comment]
same issue 
AssertionError at /server/api/salary/
'GetSalaryAPIView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.

**Comment by rshrc** [comment]
/server/api/salary/ only accepts a **POST** request. You can use postman to pass in values in the body:{} and get the output. I've run the app, and it works without any of the mentioned errors.
